spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keycloak
    username: keycloak
    password: password
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
keycloak:
  auth-server-url: http://192.168.2.101:38080/auth
  realm: WebApps
  bearer-only: true
  resource: db
  use-resource-role-mappings: true
  confidential-port: 0
  security-constraints:
      - securityCollections:
        - patterns: /demo/*
      - authRoles: user
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true

#keycloak.auth-server-url=http://127.0.0.1:38080/auth
#keycloak.realm=WebApps
#keycloak.bearer-only=true
#keycloak.resource=db
#keycloak.credentials.secret="8c9369e0-7f30-4fec-adfe-97d5e9bf2829"
#keycloak.use-resource-role-mappings=false
#keycloak.confidential-port=0
#keycloak.security-constraints[0].authRoles[0]=user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]=/demo/*